<div class="wrapper">
    <div style="height:50px"></div>
	<form action = "" method = "post" />
<div class="login fl">
        	<h2 class="dn_login">Đăng Nhập</h2>
			<p class="div_dn">Nhập Tên Đặng Nhập Và Mật Khẩu</p>
            <p class="div_title_pa">
            	<span class="div_title fl">Username:</span><input class="input_dn" name="username" type="text" />
            </p>     
            <p class="div_title_pa">
            	<span class="div_title fl">Password:</span><input class="input_dn" name="pword" type="password" />
            </p>   
             <p class="div_title_pa">
   					<span class="div_title fl">Server:</span>
                        <select class="div_title" name="">
                        	<option class="asd_bg">Chọn server...</option>
                            <option class="asd_bg">Accos</option>
                            <option class="asd_bg">Sài Gòn Petro</option>
    
                        </select>
               </p>
               <p class="div_title_pa">
    					<span class="div_title fl">Port:</span><input class="port_dn" name="" type="text" />
            </p>     
            <p class="div_title_pa">
   				<span class="div_title fl">Database:</span><input class="input_dn" name="" type="text" />
      		</p>  
            <p  style="text-align:center; margin-top:20px">
            	<span><input class="button_dn" type="submit" name = "submit" value="Đăng Nhập" /></span> 
   			 </p>    
      </div>
    	
    </form>
	<?php
			if(isset($_SESSION['error']) == TRUE){
				echo $_SESSION['error'];
				$_SESSION['error'] = '';
			}
		?>
    </div>