USE APSP;

CREATE TABLE users(
userID 		INT NOT NULL PRIMARY KEY IDENTITY(1,1),
password 	VARCHAR(128),
name 		VARCHAR(255),
active 		TINYINT DEFAULT 1
);

CREATE TABLE menus(
menuID 	INT NOT NULL PRIMARY KEY IDENTITY(1,1),
idSTT 	INT NOT NULL,
name 	NVARCHAR(255),
en		NVARCHAR(255),
vi		NVARCHAR(255),
cn		NVARCHAR(255),
level 	TINYINT DEFAULT 1
);

CREATE TABLE permission(
userID 	INT NOT NULL PRIMARY KEY,
menuID 	INT NOT NULL,
level 	TINYINT DEFAULT 1
);

ALTER TABLE permission
ADD CONSTRAINT fk_permission_userID FOREIGN KEY (userID)
REFERENCES users (userID);

ALTER TABLE permission
ADD CONSTRAINT fk_permission_menuID FOREIGN KEY (menuID)
REFERENCES menus (menuID);

CREATE TABLE languages
(
	keyLang	VARCHAR(256) NOT NULL PRIMARY KEY,
	en		NVARCHAR(256),
	vi		NVARCHAR(256),
	ch		NVARCHAR(256)
);