insert into menus(idSTT,name,level) values ('1',N'Quản Lý Nhân Sự','0')
insert into menus(idSTT,name,level) values ('2',N'Quản Lý Kinh Doanh','0')
insert into menus(idSTT,name,level) values ('3',N'Quản Lý Kho','0')
insert into menus(idSTT,name,level) values ('4',N'Quản Lý Sản Xuất','0')
insert into menus(idSTT,name,level) values ('5',N'Quản Lý Kế Toán','0')
insert into menus(idSTT,name,level) values ('6',N'Cập nhật & quản lý','1')
insert into menus(idSTT,name,level) values ('7',N' Chi tiết nhân sự','6')
insert into menus(idSTT,name,level) values ('8',N'QL Chấm Công','1')
insert into menus(idSTT,name,level) values ('9',N'Chấm Công','8')
insert into menus(idSTT,name,level) values ('10',N'QL Chấm công','1')
insert into menus(idSTT,name,level) values ('11',N'chấm công','10')
insert into menus(idSTT,name,level) values ('12',N'bc chấm công','10')
insert into menus(idSTT,name,level) values ('13',N'bc chi tiết lương','10')
insert into menus(idSTT,name,level) values ('14',N'Thông tin chi tiết','14')
insert into menus(idSTT,name,level) values ('15',N'theo dõi phát sinh','14')
insert into menus(idSTT,name,level) values ('16',N'lương hàng tháng','14')
insert into menus(idSTT,name,level) values ('17',N'bc cụ thể lương','14')
insert into menus(idSTT,name,level) values ('18',N'QL thiết bị','1')
insert into menus(idSTT,name,level) values ('19',N'theo dõi thiết bị','18')
insert into menus(idSTT,name,level) values ('20',N'bc thiết bị','18')
insert into menus(idSTT,name,level) values ('21',N'QL văn phòng phẩm','1')
insert into menus(idSTT,name,level) values ('22',N'văn phòng phẩm','21')
insert into menus(idSTT,name,level) values ('23',N'bc văn phòng phẩm ','21')
insert into menus(idSTT,name,level) values ('24',N'quản lý bán hàng','2')
insert into menus(idSTT,name,level) values ('25',N'quản lý đơn bán','24')
insert into menus(idSTT,name,level) values ('26',N'quản lý xuất bán','24')
insert into menus(idSTT,name,level) values ('27',N'quản lý giữ hộ','24')
insert into menus(idSTT,name,level) values ('28',N'QL hàng tặng','2')
insert into menus(idSTT,name,level) values ('29',N'chi tiết khuyến mãi','28')
insert into menus(idSTT,name,level) values ('30',N'QL mua hàng','2')
insert into menus(idSTT,name,level) values ('31',N'đơn hàng mua','30')
insert into menus(idSTT,name,level) values ('32',N'nhập hàng mua','30')
insert into menus(idSTT,name,level) values ('33',N'QL đơn hàng','2')
insert into menus(idSTT,name,level) values ('34',N'tờ trình bán hàng','33')
insert into menus(idSTT,name,level) values ('35',N'đơn đặt hàng','33')
insert into menus(idSTT,name,level) values ('36',N'lệnh bán hàng','33')
insert into menus(idSTT,name,level) values ('37',N'QL bán hàng','2')
insert into menus(idSTT,name,level) values ('38',N'nhập phiếu xuất','37')
insert into menus(idSTT,name,level) values ('39',N'QL hàng tặng','2')
insert into menus(idSTT,name,level) values ('40',N'chi tiết thông tin','39')
insert into menus(idSTT,name,level) values ('41',N'QL mua hàng','2')
insert into menus(idSTT,name,level) values ('42',N'đơn hàng mua','41')
insert into menus(idSTT,name,level) values ('43',N'nhập hàng mua','41')
insert into menus(idSTT,name,level) values ('44',N'QL báo cáo','2')
insert into menus(idSTT,name,level) values ('45',N'bc bán hàng','44')
insert into menus(idSTT,name,level) values ('46',N'bc mua hàng','44')
insert into menus(idSTT,name,level) values ('47',N'bc tồn và bán','44')
insert into menus(idSTT,name,level) values ('48',N'bc hàng gửi','44')
insert into menus(idSTT,name,level) values ('49',N'bc hàng khuyến mãi','44')
insert into menus(idSTT,name,level) values ('50',N'bc sản lượng','44')
insert into menus(idSTT,name,level) values ('51',N'QL kho hàng','3')
insert into menus(idSTT,name,level) values ('52',N'nhập xuất vật tư','51')
insert into menus(idSTT,name,level) values ('53',N'nhập xuất thành phẩm','51')
insert into menus(idSTT,name,level) values ('54',N'QL báo cáo','3')
insert into menus(idSTT,name,level) values ('55',N'thực nhập nguyên liệu','54')
insert into menus(idSTT,name,level) values ('56',N'xuất nguyên liệu','54')
insert into menus(idSTT,name,level) values ('57',N'nhập xuất tồn vật liệu','54')
insert into menus(idSTT,name,level) values ('58',N'nhập xuất tồn thành phẩm','54')
insert into menus(idSTT,name,level) values ('59',N'QL định mức','4')
insert into menus(idSTT,name,level) values ('60',N'định mức kỹ thuật','59')
insert into menus(idSTT,name,level) values ('61',N'lệnh sx & đặt hàng','59')
insert into menus(idSTT,name,level) values ('62',N'QL san chiết','4')
insert into menus(idSTT,name,level) values ('63',N'QL danh mục','4')
insert into menus(idSTT,name,level) values ('64',N'danh mục thành phẩm','63')
insert into menus(idSTT,name,level) values ('65',N'danh mục vật tư','63')
insert into menus(idSTT,name,level) values ('66',N'danh mục nhà cung cấp','63')
insert into menus(idSTT,name,level) values ('67',N'danh mục khách hàng','63')
insert into menus(idSTT,name,level) values ('68',N'danh mục kho hàng','63')
insert into menus(idSTT,name,level) values ('69',N'danh mục loại hàng','63')
insert into menus(idSTT,name,level) values ('70',N'danh mục loại vật tư','63')
insert into menus(idSTT,name,level) values ('71',N'QL định mức','4')
insert into menus(idSTT,name,level) values ('72',N'QL lệnh sản xuất','4')
insert into menus(idSTT,name,level) values ('73',N'QL nhập kho thành phẩm','4')
insert into menus(idSTT,name,level) values ('74',N'chứng từ nhập','73')
insert into menus(idSTT,name,level) values ('75',N'chứng từ xuất kho','73')
insert into menus(idSTT,name,level) values ('76',N'QL xuất kho','4')
insert into menus(idSTT,name,level) values ('77',N'chứng từ xuất kho','76')
insert into menus(idSTT,name,level) values ('78',N'chứng từ điều chỉnh','76')
insert into menus(idSTT,name,level) values ('79',N'chứng từ nhập trả','76')
insert into menus(idSTT,name,level) values ('80',N'QL hàng tồn kho','4')
insert into menus(idSTT,name,level) values ('81',N'QL sang chiết','4')
insert into menus(idSTT,name,level) values ('82',N'mẫu nhập chi tiết','4')
insert into menus(idSTT,name,level) values ('83',N'lệnh sản xuất','82')
insert into menus(idSTT,name,level) values ('84',N'lệnh sang chiết','82')
insert into menus(idSTT,name,level) values ('85',N'phiếu nhận hàng','82')
insert into menus(idSTT,name,level) values ('86',N'yêu cầu xuất kho','82')
insert into menus(idSTT,name,level) values ('87',N'phiếu kiểm đếm xuất hàng','82')
insert into menus(idSTT,name,level) values ('88',N'phiếu xuất kho','82')
insert into menus(idSTT,name,level) values ('89',N'QL báo cáo','4')
insert into menus(idSTT,name,level) values ('90',N'sử dụng vật liệu','89')
insert into menus(idSTT,name,level) values ('91',N'kế hoạch sản xuất','89')
insert into menus(idSTT,name,level) values ('92',N'bảng định mức sản xuất','89')
insert into menus(idSTT,name,level) values ('93',N'nhập nguyên liệu dự trù sản xuất','89')
insert into menus(idSTT,name,level) values ('94',N'sang chiết','89')
insert into menus(idSTT,name,level) values ('95',N'kiểm đếm nhận hàng','89')
insert into menus(idSTT,name,level) values ('96',N'Quản Lý Nhân Sự','5')
insert into menus(idSTT,name,level) values ('97',N'Quản Lý Kinh Doanh','0')
insert into menus(idSTT,name,level) values ('98',N'Quản Lý Kho','0')
insert into menus(idSTT,name,level) values ('99',N'Quản Lý Sản Xuất','0')
insert into menus(idSTT,name,level) values ('100',N'Quản Lý Kế Toán','0')
insert into menus(idSTT,name,level) values ('101',N'Quản Lý Nhân Sự','0')
insert into menus(idSTT,name,level) values ('102',N'Quản Lý Kinh Doanh','0')
insert into menus(idSTT,name,level) values ('103',N'Quản Lý Kho','0')
insert into menus(idSTT,name,level) values ('104',N'Quản Lý Sản Xuất','0')
insert into menus(idSTT,name,level) values ('105',N'Quản Lý Kế Toán','0')
insert into menus(idSTT,name,level) values ('106',N'Quản Lý Nhân Sự','0')
insert into menus(idSTT,name,level) values ('107',N'Quản Lý Kinh Doanh','0')
insert into menus(idSTT,name,level) values ('108',N'Quản Lý Kho','0')
insert into menus(idSTT,name,level) values ('109',N'Quản Lý Sản Xuất','0')
insert into menus(idSTT,name,level) values ('110',N'Quản Lý Kế Toán','0')
insert into menus(idSTT,name,level) values ('111',N'Quản Lý Kế Toán','0')
insert into menus(idSTT,name,level) values ('112',N'Quản Lý Kinh Doanh','0')
insert into menus(idSTT,name,level) values ('113',N'Quản Lý Kho','0')
insert into menus(idSTT,name,level) values ('114',N'Quản Lý Sản Xuất','0')
insert into menus(idSTT,name,level) values ('115',N'Quản Lý Kế Toán','0')
insert into menus(idSTT,name,level) values ('116',N'Quản Lý Nhân Sự','0')
insert into menus(idSTT,name,level) values ('117',N'Quản Lý Kinh Doanh','0')
insert into menus(idSTT,name,level) values ('118',N'Quản Lý Kho','0')
insert into menus(idSTT,name,level) values ('119',N'Quản Lý Sản Xuất','0')
insert into menus(idSTT,name,level) values ('120',N'Quản Lý Kế Toán','0')
insert into menus(idSTT,name,level) values ('121',N'Quản Lý Nhân Sự','0')
insert into menus(idSTT,name,level) values ('122',N'Quản Lý Kinh Doanh','0')
insert into menus(idSTT,name,level) values ('123',N'Quản Lý Kho','0')
insert into menus(idSTT,name,level) values ('124',N'Quản Lý Sản Xuất','0')
insert into menus(idSTT,name,level) values ('125',N'Quản Lý Kế Toán','0')
insert into menus(idSTT,name,level) values ('126',N'Quản Lý Nhân Sự','0')
insert into menus(idSTT,name,level) values ('127',N'Quản Lý Kinh Doanh','0')
insert into menus(idSTT,name,level) values ('128',N'Quản Lý Kho','0')
insert into menus(idSTT,name,level) values ('129',N'Quản Lý Sản Xuất','0')
insert into menus(idSTT,name,level) values ('130',N'Quản Lý Kế Toán','0')
insert into menus(idSTT,name,level) values ('131',N'Quản Lý Nhân Sự','0')
insert into menus(idSTT,name,level) values ('132',N'Quản Lý Kinh Doanh','0')
insert into menus(idSTT,name,level) values ('133',N'Quản Lý Kho','0')
insert into menus(idSTT,name,level) values ('134',N'Quản Lý Sản Xuất','0')
insert into menus(idSTT,name,level) values ('135',N'Quản Lý Kế Toán','0')
insert into menus(idSTT,name,level) values ('136',N'Quản Lý Nhân Sự','0')
insert into menus(idSTT,name,level) values ('137',N'Quản Lý Kinh Doanh','0')
insert into menus(idSTT,name,level) values ('138',N'Quản Lý Kho','0')
insert into menus(idSTT,name,level) values ('139',N'Quản Lý Sản Xuất','0')
insert into menus(idSTT,name,level) values ('140',N'Quản Lý Kế Toán','0')
insert into menus(idSTT,name,level) values ('141',N'Quản Lý Nhân Sự','0')
insert into menus(idSTT,name,level) values ('142',N'Quản Lý Kinh Doanh','0')
insert into menus(idSTT,name,level) values ('143',N'Quản Lý Kho','0')
insert into menus(idSTT,name,level) values ('144',N'Quản Lý Sản Xuất','0')
insert into menus(idSTT,name,level) values ('145',N'Quản Lý Kế Toán','0')
insert into menus(idSTT,name,level) values ('146',N'Quản Lý Nhân Sự','0')
insert into menus(idSTT,name,level) values ('147',N'Quản Lý Kinh Doanh','0')
insert into menus(idSTT,name,level) values ('148',N'Quản Lý Kho','0')
insert into menus(idSTT,name,level) values ('149',N'Quản Lý Sản Xuất','0')
insert into menus(idSTT,name,level) values ('150',N'Quản Lý Kế Toán','0')
insert into menus(idSTT,name,level) values ('151',N'Quản Lý Nhân Sự','0')
insert into menus(idSTT,name,level) values ('152',N'Quản Lý Kinh Doanh','0')
insert into menus(idSTT,name,level) values ('153',N'Quản Lý Kho','0')
insert into menus(idSTT,name,level) values ('154',N'Quản Lý Sản Xuất','0')
insert into menus(idSTT,name,level) values ('155',N'Quản Lý Kế Toán','0')
insert into menus(idSTT,name,level) values ('156',N'Quản Lý Nhân Sự','0')
insert into menus(idSTT,name,level) values ('157',N'Quản Lý Kinh Doanh','0')
insert into menus(idSTT,name,level) values ('158',N'Quản Lý Kho','0')
insert into menus(idSTT,name,level) values ('159',N'Quản Lý Sản Xuất','0')
insert into menus(idSTT,name,level) values ('160',N'Quản Lý Kế Toán','0')
insert into menus(idSTT,name,level) values ('161',N'Quản Lý Nhân Sự','0')
insert into menus(idSTT,name,level) values ('162',N'Quản Lý Kinh Doanh','0')
insert into menus(idSTT,name,level) values ('163',N'Quản Lý Kho','0')
insert into menus(idSTT,name,level) values ('164',N'Quản Lý Sản Xuất','0')
insert into menus(idSTT,name,level) values ('165',N'Quản Lý Kế Toán','0')
insert into menus(idSTT,name,level) values ('166',N'Quản Lý Nhân Sự','0')
insert into menus(idSTT,name,level) values ('167',N'Quản Lý Kinh Doanh','0')
insert into menus(idSTT,name,level) values ('168',N'Quản Lý Kho','0')
insert into menus(idSTT,name,level) values ('169',N'Quản Lý Sản Xuất','0')
insert into menus(idSTT,name,level) values ('170',N'Quản Lý Kế Toán','0')
insert into menus(idSTT,name,level) values ('171',N'Quản Lý Nhân Sự','0')
insert into menus(idSTT,name,level) values ('172',N'Quản Lý Kinh Doanh','0')
insert into menus(idSTT,name,level) values ('173',N'Quản Lý Kho','0')
insert into menus(idSTT,name,level) values ('174',N'Quản Lý Sản Xuất','0')
insert into menus(idSTT,name,level) values ('175',N'Quản Lý Kế Toán','0')
insert into menus(idSTT,name,level) values ('176',N'Quản Lý Nhân Sự','0')
insert into menus(idSTT,name,level) values ('177',N'Quản Lý Kinh Doanh','0')
insert into menus(idSTT,name,level) values ('178',N'Quản Lý Kho','0')
insert into menus(idSTT,name,level) values ('179',N'Quản Lý Sản Xuất','0')
insert into menus(idSTT,name,level) values ('180',N'Quản Lý Kế Toán','0')